all:
  children:
    master: # group-1
      hosts:
        master-node:
          ansible_host: 10.0.2.156
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/aws-ssh-key.pem  # To connect via SSH to master, use this key file

    slaves: # group-1
      children:
        frontend: # group-1
          hosts:
            frontend-node:
              ansible_host: 10.0.1.90
              ansible_user: ansible
              ansible_ssh_private_key_file: /home/ubuntu/.ssh/aws-ssh-key.pem  # To connect via SSH to (frontend), use this key file
        backend: # group-1
          hosts:
            backend-node-1a:
              ansible_host: 10.0.3.229
              ansible_user: ansible
              ansible_ssh_private_key_file: /home/ubuntu/.ssh/aws-ssh-key.pem  # To connect via SSH to (backend), use this key file
            backend-node-1b:
              ansible_host: 10.0.4.66
              ansible_user: ansible
              ansible_ssh_private_key_file: /home/ubuntu/.ssh/aws-ssh-key.pem  # To connect via SSH to (backend), use this key file
